version: "3.7"

services:
  firstmicroservice:
    image: mycompany/firstmicroservice:0.0.1-SNAPSHOT
    container_name: first_microservice
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://datasource:3306/first_microservice
    depends_on:
      - datasource
    restart: on-failure
    networks:
      backend:
        aliases:
            - "firstmicroservice"

  datasource:
    image: mysql
    container_name: first_microservice_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: first_microservice
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge