version: "3.7"

services:
  firstmicroservice:
    image: mycompany/firstmicroservice:0.0.1-SNAPSHOT
    container_name: first_microservice
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://datasource:3306/first_microservice
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8071/
      - SPRING_APPLICATION_NAME=firstmicroservice
    depends_on:
      - config-server
      - datasource
    restart: on-failure
    networks:
      backend:
        aliases:
            - "firstmicroservice"

  config-server:
    image: mycompany/firstspringconfigurationserver:0.0.1-SNAPSHOT
    container_name: config-server
    environment:
      - SPRING_PROFILES_ACTIVE=git
      - SPRING_APPLICATION_NAME=config-server
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/zakaria-shahen/firstspringconfigurationserver
      - SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH-PATH=src/main/resources/config
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
            - "config-server"


  datasource:
    image: mysql
    container_name: first_microservice_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: first_microservice
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge